import { setupLink, sourceLink } from './report-model';
export default function ArchitecturePanel() {
    const stages = [
        ['01', 'Question & scope', 'Validate the metric, cohort, window and task. Clarify or abstain when the question falls outside the supported contracts.', 'api/index.py'],
        ['02', 'Local retrieval', 'A pinned MiniLM model ranks versioned metric contracts using cosine similarity. No paid embedding service.', 'backend/retrieval.py'],
        ['03', 'Bounded controller', 'LangGraph selects allowlisted analytical actions. Retail follows a fixed workflow. The model never supplies executable SQL.', 'backend/agent.py'],
        ['04', 'SQL & statistics', 'Parameterized DuckDB tools compute the evidence. Independent record-level references check the numerical results.', 'backend/tools.py'],
        ['05', 'Cited answer & checks', 'The current generator selects verified facts; the server renders their numbers. Reference checks do not prove qualitative meaning.', 'backend/generation.py'],
    ];
    return <section className="architecture-view"><div className="section-intro"><div><span className="section-index">SYSTEM DESIGN</span><h2>A small system. Clear boundaries.</h2></div><p>Next.js interface. FastAPI boundary. A bounded analytical workflow with inspectable evidence at every step.</p></div><div className="architecture-flow">{stages.map(([index, title, description, path]) => <article key={index}><span className="architecture-number">{index}</span><div><h3>{title}</h3><p>{description}</p><a href={sourceLink(path)}>Read the implementation ↗</a></div></article>)}</div><div className="architecture-details"><section><h3>Two distinct datasets</h3><p><strong>Synthetic SaaS:</strong> 12,000 users and 50,504 events support activation, ordered funnels and user-level experiments. Fully documented, reproducible inputs.</p><p><strong>Public retail:</strong> 541,909 historical UCI invoice lines are reduced to month-country aggregates. The metric is gross positive sales under a disclosed exclusion policy.</p><a href={sourceLink('docs/DATA_AND_METRICS.md')}>Metric definitions ↗</a> · <a href={sourceLink('docs/REAL_DATA.md')}>Data source & audit ↗</a></section><section><h3>Safety belongs in code</h3><ul><li>Allowlisted tools and validated arguments</li><li>No model-generated SQL or shell execution</li><li>Deadlines, finite calls and persistent spend reservations</li><li>Public live mode requires shared durable quotas</li><li>Provider failures and unsupported claims fail closed</li></ul><a href={sourceLink('docs/RAG_IMPLEMENTATION.md')}>Grounding & spending controls ↗</a></section></div><div className="ownership-note"><h3>Built to be inspected.</h3><p>AI-assisted implementation at the repository owner’s request. This project demonstrates its measured engineering scope; it does not claim independent hand-authorship, real customer adoption or business uplift.</p><div><a href={sourceLink('docs/INTERVIEW_GUIDE.md')}>Explanation guide ↗</a><a href={setupLink}>Reproduce the project ↗</a><a href={sourceLink('LICENSE')}>MIT code license ↗</a></div></div></section>;
}
